/* tslint:disable */
/* eslint-disable */
/**
 * go-typescript-OpenAPI
 * praction api schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoodMorning
 */
export interface GoodMorning {
    /**
     * 
     * @type {string}
     * @memberof GoodMorning
     */
    message: string;
}

export function GoodMorningFromJSON(json: any): GoodMorning {
    return GoodMorningFromJSONTyped(json, false);
}

export function GoodMorningFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoodMorning {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GoodMorningToJSON(value?: GoodMorning | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

