/* tslint:disable */
/* eslint-disable */
/**
 * go-typescript-OpenAPI
 * praction api schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GoodMorning,
    GoodMorningFromJSON,
    GoodMorningFromJSONTyped,
    GoodMorningToJSON,
} from './GoodMorning';

/**
 * 
 * @export
 * @interface GoodMorningResponse
 */
export interface GoodMorningResponse {
    /**
     * 
     * @type {string}
     * @memberof GoodMorningResponse
     */
    message: string;
}

export function GoodMorningResponseFromJSON(json: any): GoodMorningResponse {
    return GoodMorningResponseFromJSONTyped(json, false);
}

export function GoodMorningResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoodMorningResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function GoodMorningResponseToJSON(value?: GoodMorningResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

