/* tslint:disable */
/* eslint-disable */
/**
 * go-typescript-OpenAPI
 * praction api schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GoodMorningResponse,
    GoodMorningResponseFromJSON,
    GoodMorningResponseToJSON,
} from '../models';

/**
 * 
 */
export class GoodMorningApi extends runtime.BaseAPI {

    /**
     * goodMorning api
     * return message
     */
    async goodMorningRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<GoodMorningResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/goodMorning`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GoodMorningResponseFromJSON(jsonValue));
    }

    /**
     * goodMorning api
     * return message
     */
    async goodMorning(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GoodMorningResponse> {
        const response = await this.goodMorningRaw(initOverrides);
        return await response.value();
    }

}
