/* tslint:disable */
/* eslint-disable */
/**
 * go-typescript-OpenAPI
 * praction api schema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HelloResponse,
    HelloResponseFromJSON,
    HelloResponseToJSON,
} from '../models';

export interface HelloRequest {
    tags: Array<string>;
    limit: number;
}

/**
 * 
 */
export class HelloApi extends runtime.BaseAPI {

    /**
     * hello api
     * return message
     */
    async helloRaw(requestParameters: HelloRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<HelloResponse>> {
        if (requestParameters.tags === null || requestParameters.tags === undefined) {
            throw new runtime.RequiredError('tags','Required parameter requestParameters.tags was null or undefined when calling hello.');
        }

        if (requestParameters.limit === null || requestParameters.limit === undefined) {
            throw new runtime.RequiredError('limit','Required parameter requestParameters.limit was null or undefined when calling hello.');
        }

        const queryParameters: any = {};

        if (requestParameters.tags) {
            queryParameters['tags'] = requestParameters.tags;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hello`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HelloResponseFromJSON(jsonValue));
    }

    /**
     * hello api
     * return message
     */
    async hello(requestParameters: HelloRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<HelloResponse> {
        const response = await this.helloRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
