// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// GoodMorning defines model for GoodMorning.
type GoodMorning struct {
	Message Message `json:"message"`
}

// GoodMorningResponse defines model for GoodMorningResponse.
type GoodMorningResponse struct {
	Message Message `json:"message"`
}

// Hello defines model for Hello.
type Hello struct {
	Message Message `json:"message"`
}

// HelloResponse defines model for HelloResponse.
type HelloResponse struct {
	Message Message `json:"message"`
}

// Message defines model for message.
type Message = string

// HelloParams defines parameters for Hello.
type HelloParams struct {
	// tags to filter by
	Tags []string `form:"tags" json:"tags"`

	// maximum number of results to return
	Limit int32 `form:"limit" json:"limit"`
}
