// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RUS2/bMAz+Kwa3oxt7zc23HYath6HDrkUOqkM7KvQqRRcNCv/3gVKcOo+mGLAN2MmS",
	"+fg+kR/5Aq23wTt0HKF5gdhu0Kp0/ELkSQ6BfEBijel369co3zXGlnRg7R002blIthI6T1YxNKAdL6+h",
	"BN4GzFfskWAswWKMqn8z0WTeh0Ym7XoYxxIIHwdNuIbmDnaAk/tqLOGr9+vvnpy4n5CfwX4k7KCBD9Vr",
	"Aard66vJ7Rhuj7Pn5e8fsGU4xP2JMXgXE4wy5raD5u4y4Jz0KK/4hsb4f8o/If4+80w0cZ6Rw2dlgxGA",
	"6XTaybEE7Tp/KoFAqpVjoYIuMo6Ea04Je38lmXLA1W1A9/nHDZTwhBRz/KdFvajlST6gU0FDA8tFvVhC",
	"CUHxJhWy6g9l0iOfEpn5CBdIGUmJ9WYNzYHUpNC5din/dV3nYXGMLqVWIRjdpuDqIUr+adre6+Y5ZaXy",
	"HbIlTKbimHVy7NRg+I8xyqvhDIfB4XPAlnFd4M6nhDhYq2ibKPJAbj7dqo8izHk3VhJTbaYBONuZZD3b",
	"k6xH6TQpi4wUk4QPwwW2YF902jBScb8F0SI08DggycUpizs/mI8Q04DlrEia0aZ+H4l7r3ZFpLZyj7xN",
	"8pXdCGN5zMiqZ20HW7jB3iMVvisI42A40cxle4Oj0VbzRZLvruNx9RfVe7hXLuj2taf/g2KzPlcpY0R6",
	"moQ2kBF9Moemqoxvldn4yM2yrmvZkr8CAAD//2JjgNpwBwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
